CREATE DATABASE KURS
USE KURS

CREATE TABLE STUDENTS(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50),
Age INT)

INSERT INTO STUDENTS VALUES ('Jale',20),
('Ilknur',19)

SELECT Name FROM STUDENTS

SELECT * FROM STUDENTS
